#server.port=8088

spring.data.mongodb.uri=mongodb+srv://costumeauraadmin:Pad3425ma@costumeaura-cluster.sc8epse.mongodb.net/rentacostume_reviews?retryWrites=true&w=majority&appName=costumeaura-cluster
server.port=${PORT:8088}


#spring.data.mongodb.uri=mongodb://localhost:27017/rentacostume_reviews
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

spring.kafka.bootstrap-servers=localhost:9092
rentacostume.kafka.topics.review.created=review.created.topic
rentacostume.kafka.topics.review.updated=review.updated.topic
rentacostume.kafka.topics.review.deleted=review.deleted.topic

# Feature flag: verify ?verifiedPurchase? by calling OrderService
reviews.verifyPurchase.enabled=false
#reviews.orderService.baseUrl=http://localhost:8085
rentacostume.kafka.topics.rental.completed=rentacostume.rental.completed